export const SET_SERVER_RENDER_FLAG_FALSE = 'SET_SERVER_RENDER_FLAG_FALSE'
export const SET_SERVER_RENDER_FLAG_TRUE = 'SET_SERVER_RENDER_FLAG_TRUE'

export const GET_ARTICLES_LIST_SUCCESS = 'GET_ARTICLES_LIST_SUCCESS'
export const GET_ARTICLES_NEW_FORM_SUCCESS = 'GET_ARTICLES_NEW_FORM_SUCCESS'
export const GET_ARTICLES_SHOW_FORM_REQUEST = 'GET_ARTICLES_SHOW_FORM_REQUEST'
export const GET_ARTICLES_SHOW_FORM_SUCCESS = 'GET_ARTICLES_SHOW_FORM_SUCCESS'
export const GET_ARTICLES_SHOW_FORM_FAILURE = 'GET_ARTICLES_SHOW_FORM_FAILURE'